// 测试入口：包含全部测试翻译单元
#include "check.h"

#include "test_ai.cpp"
#include "test_cli.cpp"
#include "test_clue.cpp"
#include "test_combat.cpp"
#include "test_front.cpp"
#include "test_peace.cpp"
#include "test_parliament.cpp"
#include "test_trade.cpp"
#include "test_commander.cpp"
#include "test_spy.cpp"
#include "test_negotiate.cpp"
#include "test_casus.cpp"
#include "test_personnel.cpp"
#include "test_gov.cpp"
#include "test_design.cpp"
#include "test_starbase.cpp"
#include "test_revolt.cpp"
#include "test_species.cpp"
#include "test_construction.cpp"
#include "test_crypto.cpp"
#include "test_rng.cpp"
#include "test_fixed.cpp"
#include "test_gen.cpp"
#include "test_items.cpp"
#include "test_market.cpp"
#include "test_replay.cpp"
#include "test_resolution.cpp"
#include "test_victory.cpp"
#include "test_techpolicy.cpp"
#include "test_save.cpp"
#include "test_mechanics.cpp"
#include "test_development.cpp"
#include "test_tickorder.cpp"

GF_TEST_MAIN()
